language: java
jdk:
  - openjdk8

sudo: required

services:
  - docker

jobs:
  include:
    - env: step=unitTests
      script:
      - sudo apt-get install jq
      # - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
      - wget -O ~/codacy-coverage-reporter-assembly-latest.jar https://oss.sonatype.org/service/local/repositories/releases/content/com/codacy/codacy-coverage-reporter/2.0.2/codacy-coverage-reporter-2.0.2-assembly.jar
      - mvn clean package -Pcoverage-report
      # Report coverage results to Codecov
      - bash <(curl -s https://codecov.io/bash)
      # Report coverage results to Codacy
      - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r ./target/site/jacoco/jacoco.xml

    - stage: Push Image (only with a tag)
      if: type != pull_request AND tag IS present
      script:
      - ./gen-scm-source.sh
      - ./push_image.sh
